# Generated by Django 4.0.3 on 2022-11-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='view_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_type', models.CharField(max_length=1)),
                ('v_id', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
                ('user', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
