# Generated by Django 5.1.2 on 2025-01-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='view_log',
        ),
    ]
