# Generated by Django 6.0.1 on 2026-01-17 14:35

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

def fill_table(apps, schema_editor):
  User = apps.get_model("auth", "user")
  Userinfo = apps.get_model("users", "userinfo")
  myuser = User.objects.first()
  if not Userinfo.objects.all().count():
    Userinfo.objects.create(user_id=myuser.id)

class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_alter_userinfo_allowed_schools_and_more'), ('users', '0003_product'), ('users', '0004_delete_product'), ('users', '0005_alter_userinfo_allowed_schools_and_more'), ('users', '0006_alter_userinfo_allowed_schools_and_more'), ('users', '0007_alter_userinfo_allowed_schools_and_more'), ('users', '0008_remove_archive_school_archive_stream'), ('users', '0009_alter_userinfo_allowed_schools_and_more'), ('users', '0010_userinfo_storage_quota'), ('users', '0011_userinfo_storage_used'), ('users', '0012_userinfo_mail_flag_quota100_and_more'), ('users', '0013_userinfo_mail_flag_discspace95'), ('users', '0014_userinfo_activation_key'), ('users', '0015_auto_20260117_1431')]

    initial = True

    dependencies = [
        ('streams', '0004_alter_stream_eve_alarm_email'),
        ('tf_workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typecode', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('made', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='streams.stream')),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('allowed_schools', models.IntegerField(default=3)),
                ('allowed_streams', models.IntegerField(default=3)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2100, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('made', models.DateTimeField(default=django.utils.timezone.now)),
                ('pay_tokens', models.IntegerField(default=5)),
                ('storage_quota', models.BigIntegerField(default=1000000000)),
                ('storage_used', models.BigIntegerField(default=0)),
                ('mail_flag_quota100', models.BooleanField(default=False)),
                ('mail_flag_quota75', models.BooleanField(default=False)),
                ('mail_flag_discspace95', models.BooleanField(default=False)),
                ('activation_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RunPython(fill_table, migrations.RunPython.noop),
    ]
