# Generated by Django 4.0.3 on 2022-11-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ws_predictions', '0002_client_comment'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='school',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='client_nr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='ws_predictions.client'),
        ),
    ]
