# Generated by Django 4.0.3 on 2022-11-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ws_predictions', '0002_client_comment'),
        ('users', '0002_remove_userinfo_counter_remove_userinfo_school_and_more'),
    ]

    operations = [
    ]
