# Generated by Django 4.0.3 on 2022-11-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userinfo_client_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='client_nr',
        ),
    ]
