# Generated by Django 4.2.1 on 2023-08-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
