# Generated by Django 4.2.5 on 2023-10-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='allowed_schools',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='allowed_streams',
            field=models.IntegerField(default=1),
        ),
    ]
