# Generated by Django 4.2.5 on 2023-12-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userinfo_allowed_schools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='allowed_schools',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='allowed_streams',
            field=models.IntegerField(default=5),
        ),
    ]
