# Generated by Django 4.1.4 on 2023-01-12 11:20

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userinfo_client_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='client_nr',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='allowed_install',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2100, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='made',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='pay_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
