# Generated by Django 4.2.5 on 2023-12-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userinfo_allowed_schools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='allowed_schools',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='allowed_streams',
            field=models.IntegerField(default=1),
        ),
    ]
