# Generated by Django 4.1.4 on 2023-01-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userinfo_client_nr_userinfo_allowed_install_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='allowed_install',
            new_name='allowed_schools',
        ),
    ]
