# Generated by Django 4.1.4 on 2023-01-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_allowed_install_userinfo_allowed_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='used_schools',
            field=models.IntegerField(default=1),
        ),
    ]
