# Generated by Django 4.2.5 on 2024-01-24 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_alter_stream_eve_alarm_email'),
        ('users', '0007_alter_userinfo_allowed_schools_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='school',
        ),
        migrations.AddField(
            model_name='archive',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='streams.stream'),
        ),
    ]
