# Generated by Django 4.2.5 on 2024-02-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_archive_school_archive_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='allowed_schools',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='allowed_streams',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pay_tokens',
            field=models.IntegerField(default=5),
        ),
    ]
