# Generated by Django 4.2.1 on 2023-05-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userinfo_used_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='allowed_streams',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='used_streams',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='used_schools',
            field=models.IntegerField(default=0),
        ),
    ]
