# Generated by Django 4.2.5 on 2024-07-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userinfo_storage_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='storage_used',
            field=models.BigIntegerField(default=0),
        ),
    ]
