# Generated by Django 4.2.5 on 2024-08-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userinfo_storage_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mail_flag_quota100',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mail_flag_quota75',
            field=models.BooleanField(default=False),
        ),
    ]
