# Generated by Django 4.2.5 on 2024-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userinfo_mail_flag_quota100_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mail_flag_discspace95',
            field=models.BooleanField(default=False),
        ),
    ]
