# Generated by Django 5.2.1 on 2025-06-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userinfo_mail_flag_discspace95'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='activation_key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
