# Generated by Django 6.0.1 on 2026-01-17 14:31

from django.db import migrations

def fill_table(apps, schema_editor):
  User = apps.get_model("auth", "user")
  Userinfo = apps.get_model("users", "userinfo")
  myuser = User.objects.first()
  if not Userinfo.objects.all().count():
    Userinfo.objects.create(user_id=myuser.id)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userinfo_activation_key'),
    ]

    operations = [
      migrations.RunPython(fill_table),
    ]
