# Generated by Django 6.0.1 on 2026-01-17 14:17

import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

def fill_table(apps, schema_editor):
    Trainer = apps.get_model("trainers", "Trainer")

    Trainer.objects.get_or_create(
        name="Trainer 1",
        defaults={
            "active": False,
            "gpu_nr": 0,
            "running": True,
        },
    )

class Migration(migrations.Migration):

    replaces = [('trainers', '0001_initial'), ('trainers', '0002_remove_fit_cpufan1_remove_fit_cpufan2_and_more'), ('trainers', '0003_model_type'), ('trainers', '0004_fit_early_stop_delta_min_fit_early_stop_patience_and_more'), ('trainers', '0005_fit_model_stop_overfit_model_type_x_in_default_and_more'), ('trainers', '0006_img_size_trainframe_img_sizes'), ('trainers', '0007_trainframe_encrypted'), ('trainers', '0008_alter_trainer_gpu_nr'), ('trainers', '0009_trainframe_deleted'), ('trainers', '0010_alter_fit_made'), ('trainers', '0011_trainer_wsid'), ('trainers', '0012_rename_cmetrics_epoch_binacc_and_more'), ('trainers', '0013_epoch_val_loss'), ('trainers', '0014_trainer_modeltype'), ('trainers', '0015_alter_trainer_modeltype_alter_trainer_t_type'), ('trainers', '0016_remove_fit_l_rate_decrement_and_more'), ('trainers', '0017_remove_fit_l_rate_ini_done'), ('trainers', '0018_remove_fit_l_rate_ini_div'), ('trainers', '0019_remove_fit_l_rate_start_mult'), ('trainers', '0020_epoch_auc_epoch_val_auc_fit_auc_fit_val_auc'), ('trainers', '0021_epoch_precision_epoch_recall_epoch_val_precision_and_more'), ('trainers', '0022_trainframe_last_fit_trainframe_pred0_and_more'), ('trainers', '0023_alter_trainframe_last_fit'), ('trainers', '0024_trainframe_trainers_tr_name_016abe_idx'), ('trainers', '0025_download'), ('trainers', '0026_remove_download_fit_nr'), ('trainers', '0027_download_school_alter_trainframe_school'), ('trainers', '0028_download_modeltype'), ('trainers', '0029_rename_modeltype_download_model_kat_and_more'), ('trainers', '0030_alter_trainframe_school'), ('trainers', '0031_trainer_inference_brake_trainer_inference_limit_and_more'), ('trainers', '0032_alter_trainframe_school'), ('trainers', '0033_remove_trainer_inference_limit'), ('trainers', '0034_remove_fit_model_dropout_and_more'), ('trainers', '0035_remove_fit_auc_remove_fit_l_rate_start_and_more'), ('trainers', '0036_remove_fit_weight_max_remove_fit_weight_min'), ('trainers', '0037_remove_epoch_auc_remove_epoch_val_auc_and_more'), ('trainers', '0038_remove_fit_early_stop_delta_min_and_more'), ('trainers', '0039_fit_model_finetuning'), ('trainers', '0040_alter_fit_model_finetuning'), ('trainers', '0041_epoch_finetuning_alter_fit_model_finetuning'), ('trainers', '0042_auto_20260117_1413')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.DateTimeField(default=django.utils.timezone.now)),
                ('minutes', models.FloatField(default=0)),
                ('school', models.IntegerField()),
                ('epochs', models.IntegerField(default=0)),
                ('nr_tr', models.IntegerField(default=0)),
                ('nr_va', models.IntegerField(default=0)),
                ('loss', models.FloatField(default=0)),
                ('binacc', models.FloatField(default=0)),
                ('val_loss', models.FloatField(default=0)),
                ('val_binacc', models.FloatField(default=0)),
                ('status', models.CharField(default='Done', max_length=10)),
                ('early_stop_patience', models.IntegerField(default=20)),
                ('model_image_augmentation', models.FloatField(default=0.0)),
                ('model_type', models.CharField(default='', max_length=50)),
                ('precision', models.FloatField(default=0)),
                ('recall', models.FloatField(default=0)),
                ('val_precision', models.FloatField(default=0)),
                ('val_recall', models.FloatField(default=0)),
                ('l_rate_max', models.FloatField(default=0.0001)),
                ('l_rate_min', models.FloatField(default=1e-07)),
                ('l_rate_target', models.FloatField(default=1e-06)),
                ('model_gamma', models.FloatField(default=1.0)),
                ('model_finetuning', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='model_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='efficientnetv2-b0', max_length=50)),
                ('x_in_default', models.IntegerField(default=224)),
                ('y_in_default', models.IntegerField(default=224)),
            ],
        ),
        migrations.CreateModel(
            name='img_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_url', models.CharField(max_length=128)),
                ('school', models.IntegerField(default=1)),
                ('model_kat', models.IntegerField(choices=[(1, 'Keras'), (2, 'LiteRT'), (3, 'LiteRTQ')], default=2, verbose_name='model type')),
                ('model_type', models.CharField(default='efficientnetv2-b0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='trainframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.DateTimeField()),
                ('school', models.IntegerField(db_default=0, default=0)),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=2)),
                ('c0', models.SmallIntegerField()),
                ('c1', models.SmallIntegerField()),
                ('c2', models.SmallIntegerField()),
                ('c3', models.SmallIntegerField()),
                ('c4', models.SmallIntegerField()),
                ('c5', models.SmallIntegerField()),
                ('c6', models.SmallIntegerField()),
                ('c7', models.SmallIntegerField()),
                ('c8', models.SmallIntegerField()),
                ('c9', models.SmallIntegerField()),
                ('checked', models.SmallIntegerField()),
                ('train_status', models.SmallIntegerField(default=0)),
                ('made_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('img_sizes', models.ManyToManyField(to='trainers.img_size')),
                ('encrypted', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('last_fit', models.IntegerField(default=-1)),
                ('pred0', models.FloatField(default=0.0)),
                ('pred1', models.FloatField(default=0.0)),
                ('pred2', models.FloatField(default=0.0)),
                ('pred3', models.FloatField(default=0.0)),
                ('pred4', models.FloatField(default=0.0)),
                ('pred5', models.FloatField(default=0.0)),
                ('pred6', models.FloatField(default=0.0)),
                ('pred7', models.FloatField(default=0.0)),
                ('pred8', models.FloatField(default=0.0)),
                ('pred9', models.FloatField(default=0.0)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'school'], name='trainers_tr_name_016abe_idx')],
            },
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(default='New Trainer', max_length=256)),
                ('t_type', models.IntegerField(choices=[(1, 'GPU'), (2, 'CPU'), (3, 'Remote'), (4, 'other')], default=2, verbose_name='trainer type')),
                ('gpu_nr', models.IntegerField(default=1, verbose_name='gpu number')),
                ('gpu_mem_limit', models.IntegerField(default=0, verbose_name='gpu mem limit')),
                ('startworking', models.CharField(default='00:00:00', max_length=8)),
                ('stopworking', models.CharField(default='24:00:00', max_length=8)),
                ('running', models.BooleanField(default=False)),
                ('wsserver', models.CharField(default='wss://django.cam-ai.eu/', max_length=255)),
                ('wsname', models.CharField(default='', max_length=50)),
                ('wspass', models.CharField(default='', max_length=50)),
                ('wsid', models.IntegerField(default=0)),
                ('modeltype', models.IntegerField(choices=[(1, 'Keras'), (2, 'LiteRT'), (3, 'LiteRTQ')], default=2, verbose_name='model type')),
                ('inference_brake', models.FloatField(default=0.0)),
                ('inference_waitingtime', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='epoch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.FloatField(default=0)),
                ('loss', models.FloatField(default=0)),
                ('binacc', models.FloatField(default=0)),
                ('val_binacc', models.FloatField(default=0)),
                ('learning_rate', models.FloatField(default=0)),
                ('fit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.fit')),
                ('val_loss', models.FloatField(default=0)),
                ('precision', models.FloatField(default=0)),
                ('recall', models.FloatField(default=0)),
                ('val_precision', models.FloatField(default=0)),
                ('val_recall', models.FloatField(default=0)),
                ('augmentation', models.FloatField(default=0.0)),
                ('gamma', models.FloatField(default=0.0)),
                ('phase', models.IntegerField(default=0)),
                ('finetuning', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.RunPython(fill_table, migrations.RunPython.noop),
    ]
