# Generated by Django 4.2.5 on 2023-11-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fit',
            name='cpufan1',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='cpufan2',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='cputemp',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='gpufan',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='gputemp',
        ),
        migrations.AlterField(
            model_name='fit',
            name='cmetrics',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fit',
            name='epochs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fit',
            name='loss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fit',
            name='minutes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fit',
            name='nr_tr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fit',
            name='nr_va',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fit',
            name='val_cmetrics',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fit',
            name='val_loss',
            field=models.FloatField(default=0),
        ),
    ]
