# Generated by Django 4.2.5 on 2023-11-09 13:40

from django.db import migrations, models

def fill_table_model_type(apps, schema_editor):
  Setting = apps.get_model("trainers", "model_type")
  if not Setting.objects.all().count():
    Setting.objects.create(name='efficientnetv2-b0')
    Setting.objects.create(name='efficientnetv2-b1')
    Setting.objects.create(name='efficientnetv2-b2')
    Setting.objects.create(name='efficientnetv2-b3')
    Setting.objects.create(name='efficientnetv2-s')
    Setting.objects.create(name='efficientnetv2-m')
    Setting.objects.create(name='efficientnetv2-l')


class Migration(migrations.Migration):

  dependencies = [
    ('trainers', '0002_remove_fit_cpufan1_remove_fit_cpufan2_and_more'),
  ]

  operations = [
    migrations.CreateModel(
      name='model_type',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(default='efficientnetv2-b0', max_length=50)),
      ],
    ),
    migrations.RunPython(fill_table_model_type),
  ]
