# Generated by Django 4.0.3 on 2022-11-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_wsname_trainer_wspass_alter_trainer_t_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='wsserver',
            field=models.CharField(default='wss://django.cam-ai.de/', max_length=255),
        ),
    ]
