# Generated by Django 4.2.5 on 2023-11-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_remove_fit_cpufan1_remove_fit_cpufan2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='efficientnetv2-b0', max_length=50)),
                ('x_in_default', models.IntegerField(default=224)),
                ('y_in_default', models.IntegerField(default=224)),
            ],
        ),
        migrations.AddField(
            model_name='fit',
            name='early_stop_delta_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='early_stop_patience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_decrement',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_delta_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_patience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_start',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_stop',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='fit',
            name='model_dropout',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='model_image_augmentation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='model_stop_overfit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fit',
            name='model_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fit',
            name='model_weight_constraint',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='model_weight_decay',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='weight_boost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='weight_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='weight_min',
            field=models.FloatField(default=0.0),
        ),
    ]
