# Generated by Django 4.2.5 on 2023-11-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fit',
            name='early_stop_delta_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='early_stop_patience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_decrement',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_delta_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_patience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_start',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_stop',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='fit',
            name='model_dropout',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='model_image_augmentation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='model_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fit',
            name='model_weight_constraint',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='model_weight_decay',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='weight_boost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='weight_max',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='weight_min',
            field=models.FloatField(default=0.0),
        ),
    ]
