# Generated by Django 4.0.3 on 2022-11-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_client_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='wsadminpass',
            field=models.CharField(default='', max_length=50),
        ),
    ]
