# Generated by Django 4.2.5 on 2023-12-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_fit_model_stop_overfit_model_type_x_in_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='trainframe',
            name='img_sizes',
            field=models.ManyToManyField(to='trainers.img_size'),
        ),
    ]
