# Generated by Django 4.2.5 on 2023-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_model_type_x_in_default_model_type_y_in_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='fit',
            name='model_stop_overfit',
            field=models.BooleanField(default=True),
        ),
    ]
