# Generated by Django 4.2.5 on 2024-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0006_img_size_trainframe_img_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainframe',
            name='encrypted',
            field=models.BooleanField(default=True),
        ),
    ]
