# Generated by Django 4.2.5 on 2024-06-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0007_trainframe_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='gpu_nr',
            field=models.IntegerField(default=1, verbose_name='gpu number'),
        ),
    ]
