# Generated by Django 4.2.5 on 2024-07-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0008_alter_trainer_gpu_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainframe',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
