# Generated by Django 4.2.5 on 2024-09-06 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0009_trainframe_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fit',
            name='made',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
