# Generated by Django 4.2.5 on 2024-09-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0010_alter_fit_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='wsid',
            field=models.IntegerField(default=0),
        ),
    ]
