# Generated by Django 5.1.2 on 2024-10-31 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0011_trainer_wsid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epoch',
            old_name='cmetrics',
            new_name='binacc',
        ),
        migrations.RenameField(
            model_name='epoch',
            old_name='val_cmetrics',
            new_name='val_binacc',
        ),
        migrations.RenameField(
            model_name='fit',
            old_name='cmetrics',
            new_name='binacc',
        ),
        migrations.RenameField(
            model_name='fit',
            old_name='val_cmetrics',
            new_name='val_binacc',
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='hit100',
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='val_hit100',
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='val_loss',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='hit100',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='val_hit100',
        ),
    ]
