# Generated by Django 5.1.2 on 2024-11-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0013_epoch_val_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='modeltype',
            field=models.IntegerField(choices=[(1, 'Keras'), (2, 'LiteRT'), (3, 'LiteRTQ')], default=3, verbose_name='model type'),
        ),
    ]
