# Generated by Django 5.1.2 on 2024-11-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0014_trainer_modeltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='modeltype',
            field=models.IntegerField(choices=[(1, 'Keras'), (2, 'LiteRT'), (3, 'LiteRTQ')], default=2, verbose_name='model type'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='t_type',
            field=models.IntegerField(choices=[(1, 'GPU'), (2, 'CPU'), (3, 'Remote'), (4, 'other')], default=2, verbose_name='trainer type'),
        ),
    ]
