# Generated by Django 5.1.2 on 2025-02-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0015_alter_trainer_modeltype_alter_trainer_t_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fit',
            name='l_rate_decrement',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='l_rate_delta_min',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='l_rate_patience',
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_divisor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_ini_div',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_ini_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_start_mult',
            field=models.FloatField(default=0.0),
        ),
    ]
