# Generated by Django 5.1.2 on 2025-02-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0016_remove_fit_l_rate_decrement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fit',
            name='l_rate_ini_done',
        ),
    ]
