# Generated by Django 5.1.2 on 2025-02-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0018_remove_fit_l_rate_ini_div'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fit',
            name='l_rate_start_mult',
        ),
    ]
