# Generated by Django 5.1.2 on 2025-02-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0019_remove_fit_l_rate_start_mult'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='auc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='epoch',
            name='val_auc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fit',
            name='auc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fit',
            name='val_auc',
            field=models.FloatField(default=0),
        ),
    ]
