# Generated by Django 5.2.1 on 2025-07-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0020_epoch_auc_epoch_val_auc_fit_auc_fit_val_auc'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='precision',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='epoch',
            name='recall',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='epoch',
            name='val_precision',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='epoch',
            name='val_recall',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fit',
            name='precision',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fit',
            name='recall',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fit',
            name='val_precision',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fit',
            name='val_recall',
            field=models.FloatField(default=0),
        ),
    ]
