# Generated by Django 5.2.1 on 2025-08-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0021_epoch_precision_epoch_recall_epoch_val_precision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainframe',
            name='last_fit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainframe',
            name='pred0',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainframe',
            name='pred1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainframe',
            name='pred2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainframe',
            name='pred3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainframe',
            name='pred4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainframe',
            name='pred5',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainframe',
            name='pred6',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainframe',
            name='pred7',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainframe',
            name='pred8',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainframe',
            name='pred9',
            field=models.FloatField(default=0.0),
        ),
    ]
