# Generated by Django 5.2.1 on 2025-08-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0022_trainframe_last_fit_trainframe_pred0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainframe',
            name='last_fit',
            field=models.IntegerField(default=-1),
        ),
    ]
