# Generated by Django 5.2.1 on 2025-09-09 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0023_alter_trainframe_last_fit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trainframe',
            index=models.Index(fields=['name', 'school'], name='trainers_tr_name_016abe_idx'),
        ),
    ]
