# Generated by Django 5.2.1 on 2025-09-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0024_trainframe_trainers_tr_name_016abe_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_nr', models.IntegerField()),
                ('dl_url', models.CharField(max_length=128)),
            ],
        ),
    ]
