# Generated by Django 5.2.1 on 2025-09-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0025_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='fit_nr',
        ),
    ]
