# Generated by Django 5.2.1 on 2025-09-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0026_remove_download_fit_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='school',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trainframe',
            name='school',
            field=models.IntegerField(),
        ),
    ]
