# Generated by Django 5.2.1 on 2025-09-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0027_download_school_alter_trainframe_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='modeltype',
            field=models.IntegerField(choices=[(1, 'Keras'), (2, 'LiteRT'), (3, 'LiteRTQ')], default=2, verbose_name='model type'),
        ),
    ]
