# Generated by Django 5.2.1 on 2025-09-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0028_download_modeltype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='modeltype',
            new_name='model_kat',
        ),
        migrations.AddField(
            model_name='download',
            name='model_type',
            field=models.CharField(default='efficientnetv2-b0', max_length=50),
        ),
    ]
