# Generated by Django 5.2.1 on 2025-11-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0029_rename_modeltype_download_model_kat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainframe',
            name='school',
            field=models.IntegerField(default=0),
        ),
    ]
