# Generated by Django 5.2.8 on 2025-11-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0030_alter_trainframe_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='inference_brake',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='inference_limit',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='inference_waitingtime',
            field=models.FloatField(default=0.0),
        ),
    ]
