# Generated by Django 5.2.8 on 2025-11-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0031_trainer_inference_brake_trainer_inference_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainframe',
            name='school',
            field=models.IntegerField(default=0),
        ),
    ]
