# Generated by Django 5.2.8 on 2025-11-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0032_alter_trainframe_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='inference_limit',
        ),
    ]
