# Generated by Django 5.2.8 on 2025-11-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0033_remove_trainer_inference_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fit',
            name='model_dropout',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='model_weight_constraint',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='model_weight_decay',
        ),
    ]
