# Generated by Django 5.2.8 on 2025-11-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0034_remove_fit_model_dropout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fit',
            name='auc',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='l_rate_start',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='l_rate_stop',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='model_stop_overfit',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='val_auc',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='weight_boost',
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_max',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='fit',
            name='l_rate_min',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='fit',
            name='start_increase_aug',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='start_reduce_lr',
            field=models.FloatField(default=0.0),
        ),
    ]
