# Generated by Django 5.2.8 on 2025-11-29 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0035_remove_fit_auc_remove_fit_l_rate_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fit',
            name='weight_max',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='weight_min',
        ),
    ]
