# Generated by Django 5.2.8 on 2025-11-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0036_remove_fit_weight_max_remove_fit_weight_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epoch',
            name='auc',
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='val_auc',
        ),
        migrations.AddField(
            model_name='epoch',
            name='augmentation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='epoch',
            name='gamma',
            field=models.FloatField(default=0.0),
        ),
    ]
