# Generated by Django 6.0 on 2025-12-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0038_remove_fit_early_stop_delta_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fit',
            name='model_finetuning',
            field=models.FloatField(default=0.0),
        ),
    ]
