# Generated by Django 6.0 on 2025-12-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0040_alter_fit_model_finetuning'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='finetuning',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fit',
            name='model_finetuning',
            field=models.IntegerField(default=-1),
        ),
    ]
