# Generated by Django 6.0.1 on 2026-01-17 14:13

from django.db import migrations

def fill_table(apps, schema_editor):
    Trainer = apps.get_model("trainers", "Trainer")

    Trainer.objects.get_or_create(
        name="Trainer 1",
        defaults={
            "active": False,
            "gpu_nr": 0,
            "running": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0041_epoch_finetuning_alter_fit_model_finetuning'),
    ]

    operations = [
        migrations.RunPython(fill_table, migrations.RunPython.noop),
    ]
