# Generated by Django 6.0.1 on 2026-05-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_squashed_0042_auto_20260117_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainframe',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
