# Generated by Django 6.0.1 on 2026-06-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0043_alter_trainframe_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='inference_brake',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='inference_waitingtime',
            field=models.FloatField(default=2.0),
        ),
    ]
