# Generated by Django 6.0.7 on 2026-09-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0044_alter_trainer_inference_brake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='bce',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='epoch',
            name='val_bce',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='bce',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fit',
            name='val_bce',
            field=models.FloatField(default=0.0),
        ),
    ]
