# Generated by Django 4.2.5 on 2023-10-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawpad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='mtype',
            field=models.CharField(default='C', max_length=1),
        ),
    ]
