# Generated by Django 6.0.1 on 2026-04-11 11:08

from django.db import migrations, models

def create_initial_plugin(apps, schema_editor):
    Plugin = apps.get_model('DEINE_APP', 'plugin')
    Plugin.objects.create(
        type='D',
        default=True,
        name='CAM-AI Generic Detector Plugin',
        version='1.0',
        maker='The CAM-AI-Team',
        copyright='GNU General Public License',
        description='Default detector plugin',
        path='/home/cam_ai/cam-ai/plugins/detectors/default/plugin.py'
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Alarm'), ('D', 'Detector'), ('T', 'Trainer')], max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=10)),
                ('maker', models.CharField(max_length=255)),
                ('copyright', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('path', models.CharField(max_length=2048)),
            ],
        ),
        migrations.RunPython(create_initial_plugin),
    ]
