# Generated by Django 6.0.1 on 2026-04-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'Alarm'), ('D', 'Detector'), ('T', 'Trainer')], max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=10)),
                ('maker', models.CharField(max_length=255)),
                ('copyright', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('path', models.CharField(max_length=2048)),
            ],
        ),
    ]
