# Generated by Django 6.0.1 on 2026-01-17 13:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def fill_table(apps, schema_editor):
  User = apps.get_model("auth", "User")
  Worker = apps.get_model("tf_workers", "Worker")
  School = apps.get_model("tf_workers", "School")

  # Create or reuse admin user
  admin, _ = User.objects.get_or_create(
    username="admin",
    defaults={
      "password": "pbkdf2_sha256$390000$S1kU2slc9jyJIPerlg0Zke$XhcjiuIc1UQY9GpuGPFFE0YSDaM7blJVxsxSZqfBRZQ=",
      "is_superuser": True,
      "first_name": "admin",
      "last_name": "admin",
      "email": "theo@tester.de",
      "is_staff": True,
      "is_active": True,
    },
  )

  # Create or reuse worker
  worker, _ = Worker.objects.get_or_create(
    name="TF-Worker 1",
    defaults={"active": True},
  )

  # Create or reuse school
  School.objects.get_or_create(
    name="Standard",
    defaults={
      "active": 1,
      "creator": admin,      # only if creator allows null or has default
      "tf_worker": worker,   # only if tf_worker allows null or has default
    },
  )

class Migration(migrations.Migration):

    replaces = [('tf_workers', '0001_initial'), ('tf_workers', '0002_worker_remote_trainer'), ('tf_workers', '0003_alter_school_patience'), ('tf_workers', '0004_alter_school_model_type'), ('tf_workers', '0005_alter_worker_remote_trainer'), ('tf_workers', '0006_rename_l_rate_min_school_l_rate_start_and_more'), ('tf_workers', '0007_school_early_stop_patience_and_more'), ('tf_workers', '0008_rename_image_augmetation_school_model_image_augmetation_and_more'), ('tf_workers', '0009_school_save_new_model'), ('tf_workers', '0010_rename_model_image_augmetation_school_model_image_augmentation'), ('tf_workers', '0011_rename_l_rate_end_school_l_rate_stop'), ('tf_workers', '0012_school_model_xin_school_model_yin'), ('tf_workers', '0013_school_model_stop_overfit'), ('tf_workers', '0014_alter_school_early_stop_delta_min_and_more'), ('tf_workers', '0015_school_model_train_type'), ('tf_workers', '0016_remove_worker_max_nr_clients'), ('tf_workers', '0017_school_encrypted'), ('tf_workers', '0018_alter_school_early_stop_patience_and_more'), ('tf_workers', '0019_alter_worker_timeout'), ('tf_workers', '0020_school_storage_quota'), ('tf_workers', '0021_alter_school_dir'), ('tf_workers', '0022_school_remote_creator_alter_school_creator'), ('tf_workers', '0023_alter_school_remote_creator_and_more'), ('tf_workers', '0024_alter_school_remote_creator'), ('tf_workers', '0025_worker_use_rtlite'), ('tf_workers', '0026_rename_use_rtlite_worker_use_litert'), ('tf_workers', '0027_alter_worker_use_litert_alter_worker_use_websocket'), ('tf_workers', '0028_remove_school_trainer_school_trainer'), ('tf_workers', '0029_rename_trainer_school_trainers'), ('tf_workers', '0030_rename_extra_runs_school_trainer_nr'), ('tf_workers', '0031_school_delegation_level'), ('tf_workers', '0032_school_l_rate_divisor_school_l_rate_ini_div_and_more'), ('tf_workers', '0033_remove_school_l_rate_decrement_and_more'), ('tf_workers', '0034_remove_school_l_rate_ini_div_and_more'), ('tf_workers', '0035_alter_school_l_rate_divisor_alter_school_l_rate_last'), ('tf_workers', '0036_remove_school_l_rate_last_and_more'), ('tf_workers', '0037_alter_school_l_rate_start_alter_school_l_rate_stop'), ('tf_workers', '0038_alter_school_l_rate_divisor_alter_worker_timeout'), ('tf_workers', '0039_alter_school_l_rate_divisor_alter_school_trainer_nr'), ('tf_workers', '0040_alter_school_l_rate_divisor'), ('tf_workers', '0041_school_last_fit'), ('tf_workers', '0042_alter_school_early_stop_patience_and_more'), ('tf_workers', '0043_alter_school_early_stop_delta_min'), ('tf_workers', '0044_alter_school_model_image_augmentation'), ('tf_workers', '0045_remove_worker_savestats'), ('tf_workers', '0046_alter_school_trigger'), ('tf_workers', '0047_school_load_last_model'), ('tf_workers', '0048_remove_school_model_dropout_and_more'), ('tf_workers', '0049_worker_use_coral'), ('tf_workers', '0050_rename_l_rate_start_school_l_rate_max_and_more'), ('tf_workers', '0051_remove_school_weight_max_remove_school_weight_min_and_more'), ('tf_workers', '0052_remove_school_early_stop_delta_min_and_more'), ('tf_workers', '0053_school_model_finetuning'), ('tf_workers', '0054_alter_school_model_finetuning'), ('tf_workers', '0055_school_last_fit_infer'), ('tf_workers', '0056_alter_school_model_finetuning'), ('tf_workers', '0057_alter_school_early_stop_patience'), ('tf_workers', '0058_auto_20260117_1253')]

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        ('trainers', '0015_alter_trainer_modeltype_alter_trainer_t_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(default='New TF-Worker', max_length=100)),
                ('maxblock', models.IntegerField(default=8)),
                ('timeout', models.FloatField(default=0.1)),
                ('max_nr_models', models.IntegerField(default=64)),
                ('gpu_sim_loading', models.FloatField(default=0.0)),
                ('gpu_sim', models.FloatField(default=-1.0)),
                ('gpu_nr', models.IntegerField(default=0)),
                ('use_websocket', models.BooleanField(default=False)),
                ('wsserver', models.CharField(default='wss://django.cam-ai.eu/', max_length=255)),
                ('wsname', models.CharField(default='', max_length=50)),
                ('wspass', models.CharField(default='', max_length=50)),
                ('wsid', models.IntegerField(default=0)),
                ('remote_trainer', models.BooleanField(default=False)),
                ('use_litert', models.BooleanField(default=True)),
                ('use_coral', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_schools', to=settings.AUTH_USER_MODEL)),
                ('dir', models.CharField(default='data/schools/model1/', max_length=256)),
                ('trigger', models.IntegerField(default=1000000)),
                ('lastmodelfile', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('active', models.IntegerField(default=1)),
                ('l_rate_max', models.FloatField(default=0.0001)),
                ('e_school', models.IntegerField(default=1)),
                ('model_type', models.CharField(default='efficientnetv2-b0', max_length=50)),
                ('ignore_checked', models.BooleanField(default=True)),
                ('trainer_nr', models.IntegerField(default=1)),
                ('donate_pics', models.BooleanField(default=False)),
                ('tf_worker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tf_workers.worker')),
                ('model_image_augmentation', models.FloatField(default=0.0)),
                ('l_rate_min', models.FloatField(default=1e-07)),
                ('early_stop_patience', models.IntegerField(default=12)),
                ('save_new_model', models.BooleanField(default=True)),
                ('model_xin', models.IntegerField(default=224)),
                ('model_yin', models.IntegerField(default=224)),
                ('model_train_type', models.CharField(default='efficientnetv2-b0', max_length=50)),
                ('encrypted', models.BooleanField(default=True)),
                ('storage_quota', models.BigIntegerField(default=1)),
                ('remote_creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='remotely_created_schools', to=settings.AUTH_USER_MODEL)),
                ('trainers', models.ManyToManyField(to='trainers.trainer')),
                ('delegation_level', models.IntegerField(default=1)),
                ('last_fit', models.IntegerField(default=0)),
                ('load_last_model', models.BooleanField(default=True)),
                ('l_rate_target', models.FloatField(default=1e-06)),
                ('model_gamma', models.FloatField(default=1.0)),
                ('model_finetuning', models.IntegerField(default=-1)),
                ('last_fit_infer', models.IntegerField(default=0)),
            ],
        ),
        migrations.RunPython(fill_table, migrations.RunPython.noop),
    ]
