# Generated by Django 4.0.3 on 2022-11-04 18:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(default='New TF-Worker', max_length=100)),
                ('maxblock', models.IntegerField(default=8)),
                ('timeout', models.FloatField(default=0.1)),
                ('max_nr_models', models.IntegerField(default=64)),
                ('max_nr_clients', models.IntegerField(default=20)),
                ('gpu_sim_loading', models.FloatField(default=0.0)),
                ('gpu_sim', models.FloatField(default=-1.0)),
                ('gpu_nr', models.IntegerField(default=0)),
                ('savestats', models.FloatField(default=0.0)),
                ('use_websocket', models.BooleanField(default=False)),
                ('wsserver', models.CharField(default='', max_length=255)),
                ('wsname', models.CharField(default='', max_length=30)),
                ('wspass', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dir', models.CharField(default='', max_length=256)),
                ('trigger', models.IntegerField(default=500)),
                ('lastmodelfile', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc))),
                ('active', models.IntegerField(default=1)),
                ('l_rate_min', models.CharField(default='-1', max_length=20)),
                ('l_rate_max', models.CharField(default='-1', max_length=20)),
                ('e_school', models.IntegerField(default=1)),
                ('model_type', models.CharField(default='cam-ai_model', max_length=50)),
                ('ignore_checked', models.BooleanField(default=False)),
                ('extra_runs', models.IntegerField(default=0)),
                ('donate_pics', models.BooleanField(default=True)),
                ('weight_max', models.FloatField(default=2.0)),
                ('weight_min', models.FloatField(default=1.0)),
                ('weight_boost', models.FloatField(default=1.0)),
                ('patience', models.IntegerField(default=6)),
                ('tf_worker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tf_workers.worker')),
                ('trainer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='trainers.trainer')),
            ],
        ),
    ]
