# Generated by Django 4.2.1 on 2023-07-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='remote_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
