# Generated by Django 4.0.3 on 2022-11-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='donate_pics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='l_rate_max',
            field=models.CharField(default='1e-6', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='l_rate_min',
            field=models.CharField(default='1e-6', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='model_type',
            field=models.CharField(default='efficientnetv2b0', max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='max_nr_clients',
            field=models.IntegerField(default=64),
        ),
        migrations.AlterField(
            model_name='worker',
            name='use_websocket',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wsname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wspass',
            field=models.CharField(default='', max_length=50),
        ),
    ]
