# Generated by Django 4.0.3 on 2022-11-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0002_alter_school_donate_pics_alter_school_l_rate_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='weight_boost',
            field=models.FloatField(default=8.0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='wsserver',
            field=models.CharField(default='wss://django.cam-ai.de/', max_length=255),
        ),
    ]
