# Generated by Django 4.2.5 on 2023-09-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0002_worker_remote_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='patience',
            field=models.IntegerField(default=10),
        ),
    ]
