# Generated by Django 4.2.5 on 2023-10-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0003_alter_school_patience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='model_type',
            field=models.CharField(default='efficientnetv2-b0', max_length=50),
        ),
    ]
