# Generated by Django 4.2.5 on 2023-10-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0004_alter_school_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='remote_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
