# Generated by Django 4.0.3 on 2022-11-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0004_worker_wsadminpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='wsid',
            field=models.IntegerField(default=0),
        ),
    ]
