# Generated by Django 4.2.5 on 2023-11-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0005_alter_worker_remote_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='l_rate_min',
            new_name='l_rate_start',
        ),
        migrations.RemoveField(
            model_name='school',
            name='l_rate_max',
        ),
        migrations.RemoveField(
            model_name='school',
            name='patience',
        ),
        migrations.AddField(
            model_name='school',
            name='early_stop_delta_min',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='school',
            name='image_augmetation',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='school',
            name='l_rate_decrement',
            field=models.FloatField(default=0.31622776601683794),
        ),
        migrations.AddField(
            model_name='school',
            name='l_rate_delta_min',
            field=models.FloatField(default=1e-05),
        ),
        migrations.AddField(
            model_name='school',
            name='l_rate_end',
            field=models.CharField(default='1e-7', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='l_rate_patience',
            field=models.IntegerField(default=3),
        ),
    ]
