# Generated by Django 4.1.4 on 2023-01-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0005_worker_wsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='wsadminpass',
        ),
    ]
