# Generated by Django 4.1.5 on 2023-02-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0006_remove_worker_wsadminpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='ignore_checked',
            field=models.BooleanField(default=True),
        ),
    ]
