# Generated by Django 4.2.5 on 2023-11-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0006_rename_l_rate_min_school_l_rate_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='early_stop_patience',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='early_stop_delta_min',
            field=models.FloatField(default=1e-05),
        ),
    ]
