# Generated by Django 4.2.5 on 2023-11-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0008_rename_image_augmetation_school_model_image_augmetation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='save_new_model',
            field=models.BooleanField(default=True),
        ),
    ]
