# Generated by Django 4.2.5 on 2023-11-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0009_school_save_new_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='model_image_augmetation',
            new_name='model_image_augmentation',
        ),
    ]
