# Generated by Django 4.2.5 on 2023-11-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0010_rename_model_image_augmetation_school_model_image_augmentation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='l_rate_end',
            new_name='l_rate_stop',
        ),
    ]
