# Generated by Django 4.2.5 on 2023-11-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0011_rename_l_rate_end_school_l_rate_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='model_xin',
            field=models.IntegerField(default=224),
        ),
        migrations.AddField(
            model_name='school',
            name='model_yin',
            field=models.IntegerField(default=224),
        ),
    ]
