# Generated by Django 4.2.5 on 2023-12-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0014_alter_school_early_stop_delta_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='model_train_type',
            field=models.CharField(default='efficientnetv2-b0', max_length=50),
        ),
    ]
