# Generated by Django 4.2.5 on 2024-01-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0015_school_model_train_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='max_nr_clients',
        ),
    ]
