# Generated by Django 4.2.5 on 2024-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0016_remove_worker_max_nr_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='encrypted',
            field=models.BooleanField(default=True),
        ),
    ]
