# Generated by Django 4.2.5 on 2024-02-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0017_school_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='early_stop_patience',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='school',
            name='l_rate_start',
            field=models.CharField(default='1e-4', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='model_image_augmentation',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='school',
            name='model_weight_decay',
            field=models.FloatField(default=0.0),
        ),
    ]
