# Generated by Django 4.2.5 on 2024-09-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0020_school_storage_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='dir',
            field=models.CharField(default='data/schools/model1/', max_length=256),
        ),
    ]
