# Generated by Django 5.1.2 on 2024-11-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0025_worker_use_rtlite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='use_rtlite',
            new_name='use_litert',
        ),
    ]
