# Generated by Django 5.1.2 on 2024-11-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0026_rename_use_rtlite_worker_use_litert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='use_litert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='use_websocket',
            field=models.BooleanField(default=False),
        ),
    ]
