# Generated by Django 5.1.2 on 2025-01-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0027_alter_worker_use_litert_alter_worker_use_websocket'),
        ('trainers', '0015_alter_trainer_modeltype_alter_trainer_t_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='trainer',
        ),
        migrations.AddField(
            model_name='school',
            name='trainer',
            field=models.ManyToManyField(to='trainers.trainer'),
        ),
    ]
