# Generated by Django 5.1.2 on 2025-01-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0028_remove_school_trainer_school_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='trainer',
            new_name='trainers',
        ),
    ]
