# Generated by Django 5.1.2 on 2025-01-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0029_rename_trainer_school_trainers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='extra_runs',
            new_name='trainer_nr',
        ),
    ]
