# Generated by Django 5.1.2 on 2025-01-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0030_rename_extra_runs_school_trainer_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='delegation_level',
            field=models.IntegerField(default=1),
        ),
    ]
