# Generated by Django 5.1.2 on 2025-02-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0031_school_delegation_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='l_rate_divisor',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AddField(
            model_name='school',
            name='l_rate_ini_div',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='school',
            name='l_rate_ini_done',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='l_rate_last',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='school',
            name='l_rate_start_mult',
            field=models.FloatField(default=10.0),
        ),
    ]
