# Generated by Django 5.1.2 on 2025-02-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0032_school_l_rate_divisor_school_l_rate_ini_div_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='l_rate_decrement',
        ),
        migrations.RemoveField(
            model_name='school',
            name='l_rate_delta_min',
        ),
        migrations.RemoveField(
            model_name='school',
            name='l_rate_patience',
        ),
    ]
