# Generated by Django 5.1.2 on 2025-02-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0035_alter_school_l_rate_divisor_alter_school_l_rate_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='l_rate_last',
        ),
        migrations.RemoveField(
            model_name='school',
            name='l_rate_start_mult',
        ),
    ]
