# Generated by Django 5.1.6 on 2025-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0037_alter_school_l_rate_start_alter_school_l_rate_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='l_rate_divisor',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='timeout',
            field=models.FloatField(default=0.1),
        ),
    ]
