# Generated by Django 5.2.1 on 2025-06-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0038_alter_school_l_rate_divisor_alter_worker_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='l_rate_divisor',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AlterField(
            model_name='school',
            name='trainer_nr',
            field=models.IntegerField(default=1),
        ),
    ]
