# Generated by Django 5.2.1 on 2025-06-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0039_alter_school_l_rate_divisor_alter_school_trainer_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='l_rate_divisor',
            field=models.FloatField(default=1000.0),
        ),
    ]
