# Generated by Django 5.2.1 on 2025-08-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0040_alter_school_l_rate_divisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_fit',
            field=models.IntegerField(default=0),
        ),
    ]
