# Generated by Django 5.2.1 on 2025-10-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0041_school_last_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='early_stop_patience',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='model_image_augmentation',
            field=models.FloatField(default=0.5),
        ),
    ]
