# Generated by Django 5.2.1 on 2025-10-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0042_alter_school_early_stop_patience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='early_stop_delta_min',
            field=models.FloatField(default=0.0),
        ),
    ]
