# Generated by Django 5.2.1 on 2025-10-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0043_alter_school_early_stop_delta_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='model_image_augmentation',
            field=models.FloatField(default=0.2),
        ),
    ]
