# Generated by Django 5.2.1 on 2025-10-12 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0044_alter_school_model_image_augmentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='savestats',
        ),
    ]
