# Generated by Django 5.2.1 on 2025-10-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0045_remove_worker_savestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='trigger',
            field=models.IntegerField(default=1000000),
        ),
    ]
