# Generated by Django 5.2.1 on 2025-10-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0046_alter_school_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='load_last_model',
            field=models.BooleanField(default=True),
        ),
    ]
