# Generated by Django 5.2.8 on 2025-11-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0047_school_load_last_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='model_dropout',
        ),
        migrations.RemoveField(
            model_name='school',
            name='model_weight_constraint',
        ),
        migrations.RemoveField(
            model_name='school',
            name='model_weight_decay',
        ),
    ]
