# Generated by Django 5.2.8 on 2025-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0048_remove_school_model_dropout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='use_coral',
            field=models.BooleanField(default=False),
        ),
    ]
