# Generated by Django 5.2.8 on 2025-11-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0049_worker_use_coral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='l_rate_start',
            new_name='l_rate_max',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='l_rate_stop',
            new_name='l_rate_min',
        ),
        migrations.RemoveField(
            model_name='school',
            name='model_stop_overfit',
        ),
        migrations.RemoveField(
            model_name='school',
            name='weight_boost',
        ),
    ]
