# Generated by Django 5.2.8 on 2025-11-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0050_rename_l_rate_start_school_l_rate_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='weight_max',
        ),
        migrations.RemoveField(
            model_name='school',
            name='weight_min',
        ),
        migrations.AddField(
            model_name='school',
            name='start_increase_aug',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='school',
            name='start_reduce_lr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='school',
            name='l_rate_max',
            field=models.CharField(default='1e-3', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='l_rate_min',
            field=models.CharField(default='1e-7', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='model_image_augmentation',
            field=models.FloatField(default=0.0),
        ),
    ]
