# Generated by Django 6.0 on 2025-12-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0051_remove_school_weight_max_remove_school_weight_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='early_stop_delta_min',
        ),
        migrations.RemoveField(
            model_name='school',
            name='l_rate_divisor',
        ),
        migrations.RemoveField(
            model_name='school',
            name='start_increase_aug',
        ),
        migrations.RemoveField(
            model_name='school',
            name='start_reduce_lr',
        ),
        migrations.AddField(
            model_name='school',
            name='l_rate_target',
            field=models.FloatField(default=1e-06),
        ),
        migrations.AddField(
            model_name='school',
            name='model_gamma',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='school',
            name='l_rate_max',
            field=models.FloatField(default=0.0001),
        ),
        migrations.AlterField(
            model_name='school',
            name='l_rate_min',
            field=models.FloatField(default=1e-07),
        ),
    ]
