# Generated by Django 6.0 on 2025-12-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0052_remove_school_early_stop_delta_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='model_finetuning',
            field=models.FloatField(default=0.0),
        ),
    ]
