# Generated by Django 6.0 on 2025-12-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0053_school_model_finetuning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='model_finetuning',
            field=models.IntegerField(default=0),
        ),
    ]
