# Generated by Django 6.0 on 2025-12-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0054_alter_school_model_finetuning'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_fit_infer',
            field=models.IntegerField(default=0),
        ),
    ]
