# Generated by Django 6.0 on 2025-12-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0055_school_last_fit_infer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='model_finetuning',
            field=models.IntegerField(default=-1),
        ),
    ]
