# Generated by Django 6.0 on 2026-01-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0056_alter_school_model_finetuning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='early_stop_patience',
            field=models.IntegerField(default=12),
        ),
    ]
