# Generated by Django 6.0.1 on 2026-01-17 12:53

from django.db import migrations

def fill_table(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Worker = apps.get_model("tf_workers", "Worker")
    School = apps.get_model("tf_workers", "School")

    # Create or reuse admin user
    admin, _ = User.objects.get_or_create(
        username="admin",
        defaults={
            "password": "pbkdf2_sha256$390000$S1kU2slc9jyJIPerlg0Zke$XhcjiuIc1UQY9GpuGPFFE0YSDaM7blJVxsxSZqfBRZQ=",
            "is_superuser": True,
            "first_name": "admin",
            "last_name": "admin",
            "email": "theo@tester.de",
            "is_staff": True,
            "is_active": True,
        },
    )

    # Create or reuse worker
    worker, _ = Worker.objects.get_or_create(
        name="TF-Worker 1",
        defaults={"active": True},
    )

    # Create or reuse school
    School.objects.get_or_create(
        name="Standard",
        defaults={
            "active": 1,
            "creator": admin,      # only if creator allows null or has default
            "tf_worker": worker,   # only if tf_worker allows null or has default
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0057_alter_school_early_stop_patience'),
    ]

    operations = [
      migrations.RunPython(fill_table), 
    ]
