# Generated by Django 6.0 on 2026-01-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0057_alter_school_early_stop_patience'),
        ('trainers', '0041_epoch_finetuning_alter_fit_model_finetuning'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tf_workers_school_trainer',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='school',
            name='trainers',
            field=models.ManyToManyField(related_name='schools', through='tf_workers.SchoolTrainer', to='trainers.trainer'),
        ),
    ]
