# Generated by Django 6.0.1 on 2026-05-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0001_squashed_0058_auto_20260117_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
