# Generated by Django 6.0.1 on 2026-07-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0059_alter_school_encrypted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='use_coral',
        ),
    ]
