# Generated by Django 6.0.1 on 2026-01-17 13:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('eventers', '0001_initial'), ('eventers', '0002_event_frame_name_idx'), ('eventers', '0003_alarm'), ('eventers', '0004_alarm_name'), ('eventers', '0005_alarm_mendef_alter_alarm_action_type'), ('eventers', '0006_alarmdevice_remove_alarm_action_param1_and_more'), ('eventers', '0007_alarmdevice_remove_alarm_action_param1_and_more'), ('eventers', '0008_event_camera'), ('eventers', '0009_alter_event_xmax_alter_event_xmin_alter_event_ymax_and_more'), ('eventers', '0010_event_video_encrypted_event_frame_encrypted'), ('eventers', '0011_alarm_device_alarm_device_type_delete_alarmdevice_and_more'), ('eventers', '0012_alarm_mydevice'), ('eventers', '0013_alarm_name_alter_alarm_device_type_name'), ('eventers', '0014_alarm_active'), ('eventers', '0015_event_deleted_event_frame_deleted')]

    initial = True

    dependencies = [
        ('streams', '0001_initial'),
        ('streams', '0004_alter_stream_eve_alarm_email'),
        ('tf_workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_string', models.CharField(default='[]', max_length=255)),
                ('start', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('end', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('xmin', models.IntegerField(default=-1)),
                ('xmax', models.IntegerField(default=-1)),
                ('ymin', models.IntegerField(default=-1)),
                ('ymax', models.IntegerField(default=-1)),
                ('numframes', models.IntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('videoclip', models.CharField(default='', max_length=256)),
                ('double', models.BooleanField(default=False)),
                ('hasarchive', models.BooleanField(default=False)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tf_workers.school')),
                ('camera', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streams.stream')),
                ('video_encrypted', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='evt_condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField(choices=[(1, 'show frame'), (2, 'send school'), (3, 'record video'), (4, 'send email'), (5, 'alarm')], default=0, verbose_name='reaction')),
                ('and_or', models.IntegerField(choices=[(1, 'and'), (2, 'or')], default=2, verbose_name='and_or')),
                ('c_type', models.IntegerField(choices=[(1, 'any movement detection'), (2, 'x values above or equal y'), (3, 'x values below or equal y'), (4, 'tag x is above or equal y'), (5, 'tag x is below or equal y'), (6, 'tag x is in top y')], default=1, verbose_name='c_type')),
                ('x', models.IntegerField(default=1, verbose_name='x')),
                ('y', models.FloatField(default=0.5, verbose_name='y')),
                ('bracket', models.IntegerField(default=0, verbose_name='bracket')),
                ('eventer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.stream')),
            ],
        ),
        migrations.CreateModel(
            name='alarm_device_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New device type', max_length=50)),
                ('mendef', models.CharField(default='[]', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='alarm_device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New device', max_length=50)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventers.alarm_device_type')),
            ],
        ),
        migrations.CreateModel(
            name='alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mendef', models.CharField(default='[]', max_length=255)),
                ('mystream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streams.stream')),
                ('mydevice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventers.alarm_device')),
                ('name', models.CharField(default='New alarm', max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='event_frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('status', models.SmallIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('x1', models.IntegerField(default=0)),
                ('x2', models.IntegerField(default=0)),
                ('y1', models.IntegerField(default=0)),
                ('y2', models.IntegerField(default=0)),
                ('trainframe', models.BigIntegerField(default=0)),
                ('hasarchive', models.BooleanField(default=False)),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventers.event')),
                ('encrypted', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='name_idx')],
            },
        ),
    ]
