# Generated by Django 4.2.1 on 2023-07-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event_frame',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
