# Generated by Django 4.2.5 on 2023-11-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventers', '0002_event_frame_name_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.IntegerField(choices=[(1, 'action1'), (2, 'action2'), (3, 'action3')], default=0, verbose_name='action_type')),
                ('action_param1', models.CharField(max_length=20)),
                ('action_param2', models.CharField(max_length=20)),
            ],
        ),
    ]
