# Generated by Django 4.2.5 on 2023-11-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventers', '0004_alarm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='mendef',
            field=models.CharField(default='[]', max_length=255),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='action_type',
            field=models.IntegerField(choices=[(1, 'USB Relais'), (2, 'Philips HUE'), (3, 'action3')], default=0, verbose_name='action_type'),
        ),
    ]
