# Generated by Django 4.2.5 on 2023-12-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_alter_stream_eve_alarm_email'),
        ('eventers', '0005_alarm_mendef_alter_alarm_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarmdevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New device', max_length=50)),
                ('mendef', models.CharField(default='[]', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='action_param1',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='action_param2',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='name',
        ),
        migrations.AddField(
            model_name='alarm',
            name='mystream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streams.stream'),
        ),
    ]
