# Generated by Django 4.2.5 on 2024-01-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_alter_stream_eve_alarm_email'),
        ('eventers', '0007_alarmdevice_remove_alarm_action_param1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streams.stream'),
        ),
    ]
