# Generated by Django 4.2.5 on 2024-02-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventers', '0008_event_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='xmax',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='event',
            name='xmin',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='event',
            name='ymax',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='event',
            name='ymin',
            field=models.IntegerField(default=-1),
        ),
    ]
