# Generated by Django 4.2.5 on 2024-04-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventers', '0010_event_video_encrypted_event_frame_encrypted'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarm_device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New device', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='alarm_device_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New device', max_length=50)),
                ('mendef', models.CharField(default='[]', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='alarmdevice',
        ),
        migrations.AddField(
            model_name='alarm_device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventers.alarm_device_type'),
        ),
    ]
