# Generated by Django 4.2.5 on 2024-04-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventers', '0011_alarm_device_alarm_device_type_delete_alarmdevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='mydevice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventers.alarm_device'),
        ),
    ]
