# Generated by Django 4.2.5 on 2024-04-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventers', '0013_alarm_name_alter_alarm_device_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
