# Generated by Django 4.2.5 on 2024-07-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventers', '0014_alarm_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event_frame',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
