# Generated by Django 6.0.1 on 2026-05-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventers', '0001_squashed_0015_event_deleted_event_frame_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event_frame',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
