# Generated by Django 6.0.1 on 2026-01-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('cleanup', '0001_initial'), ('cleanup', '0002_rename_name_events_frames_missingdbline_idx_and_more'), ('cleanup', '0003_files_to_delete_delete_events_frames_missingdbline_and_more'), ('cleanup', '0004_status_line_stream'), ('cleanup', '0005_status_line_event_status_line_school_and_more'), ('cleanup', '0006_remove_status_line_event_video_correct_and_more'), ('cleanup', '0007_status_line_video_video_jpg_and_more'), ('cleanup', '0008_rename_video_correct_status_line_video_videos_correct_and_more'), ('cleanup', '0009_files_to_delete_min_age'), ('cleanup', '0010_status_line_event_events_temp'), ('cleanup', '0011_remove_status_line_event_stream_and_more')]

    initial = True

    dependencies = [
        ('streams', '0016_alter_stream_cam_checkdoubles_and_more'),
        ('tf_workers', '0019_alter_worker_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='files_to_delete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('min_age', models.FloatField(default=0.0)),
            ],
        ),
    ]
