# Generated by Django 4.2.5 on 2024-07-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events_frames_missingdbline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='events_frames_missingframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='status_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.DateTimeField()),
                ('events_frames_correct', models.BigIntegerField(default=0)),
                ('events_frames_missingframes', models.BigIntegerField(default=0)),
                ('events_frames_missingevents', models.BigIntegerField(default=0)),
            ],
        ),
    ]
