# Generated by Django 4.2.5 on 2024-07-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events_frames_missingdbline',
            old_name='name',
            new_name='idx',
        ),
        migrations.RenameField(
            model_name='events_frames_missingframe',
            old_name='name',
            new_name='idx',
        ),
    ]
