# Generated by Django 4.2.5 on 2024-07-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0016_alter_stream_cam_checkdoubles_and_more'),
        ('cleanup', '0003_files_to_delete_delete_events_frames_missingdbline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_line',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streams.stream'),
        ),
    ]
