# Generated by Django 4.2.5 on 2024-07-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tf_workers', '0019_alter_worker_timeout'),
        ('streams', '0016_alter_stream_cam_checkdoubles_and_more'),
        ('cleanup', '0004_status_line_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='status_line_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.DateTimeField()),
                ('events_frames_correct', models.BigIntegerField(default=0)),
                ('events_frames_missingframes', models.BigIntegerField(default=0)),
                ('eframes_correct', models.BigIntegerField(default=0)),
                ('eframes_missingdb', models.BigIntegerField(default=0)),
                ('eframes_missingfiles', models.BigIntegerField(default=0)),
                ('video_correct', models.BigIntegerField(default=0)),
                ('video_temp', models.BigIntegerField(default=0)),
                ('video_missingfiles', models.BigIntegerField(default=0)),
                ('stream', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streams.stream')),
            ],
        ),
        migrations.CreateModel(
            name='status_line_school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.DateTimeField()),
                ('schools_correct', models.BigIntegerField(default=0)),
                ('schools_missingdb', models.BigIntegerField(default=0)),
                ('schools_missingfiles', models.BigIntegerField(default=0)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tf_workers.school')),
            ],
        ),
        migrations.CreateModel(
            name='status_line_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made', models.DateTimeField()),
                ('video_missingdb', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='status_line',
        ),
    ]
