# Generated by Django 4.2.5 on 2024-07-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanup', '0005_status_line_event_status_line_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status_line_event',
            name='video_correct',
        ),
        migrations.RemoveField(
            model_name='status_line_event',
            name='video_missingfiles',
        ),
        migrations.RemoveField(
            model_name='status_line_event',
            name='video_temp',
        ),
        migrations.AddField(
            model_name='status_line_video',
            name='video_correct',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status_line_video',
            name='video_missingfiles',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status_line_video',
            name='video_temp',
            field=models.BigIntegerField(default=0),
        ),
    ]
