# Generated by Django 4.2.5 on 2024-07-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanup', '0006_remove_status_line_event_video_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_line_video',
            name='video_jpg',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status_line_video',
            name='video_mp4',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status_line_video',
            name='video_webm',
            field=models.BigIntegerField(default=0),
        ),
    ]
