# Generated by Django 4.2.5 on 2024-07-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanup', '0007_status_line_video_video_jpg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status_line_video',
            old_name='video_correct',
            new_name='videos_correct',
        ),
        migrations.RenameField(
            model_name='status_line_video',
            old_name='video_jpg',
            new_name='videos_jpg',
        ),
        migrations.RenameField(
            model_name='status_line_video',
            old_name='video_missingdb',
            new_name='videos_missingdb',
        ),
        migrations.RenameField(
            model_name='status_line_video',
            old_name='video_missingfiles',
            new_name='videos_missingfiles',
        ),
        migrations.RenameField(
            model_name='status_line_video',
            old_name='video_mp4',
            new_name='videos_mp4',
        ),
        migrations.RenameField(
            model_name='status_line_video',
            old_name='video_temp',
            new_name='videos_temp',
        ),
        migrations.RenameField(
            model_name='status_line_video',
            old_name='video_webm',
            new_name='videos_webm',
        ),
    ]
