# Generated by Django 4.2.5 on 2024-07-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleanup', '0009_files_to_delete_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_line_event',
            name='events_temp',
            field=models.BigIntegerField(default=0),
        ),
    ]
