# Generated by Django 5.2.1 on 2025-10-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleanup', '0010_status_line_event_events_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status_line_event',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='status_line_school',
            name='school',
        ),
        migrations.DeleteModel(
            name='status_line_video',
        ),
        migrations.DeleteModel(
            name='status_line_event',
        ),
        migrations.DeleteModel(
            name='status_line_school',
        ),
    ]
