# Generated by Django 4.0.3 on 2022-11-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('school', models.SmallIntegerField(default=0)),
                ('replaces', models.SmallIntegerField(default=-1)),
            ],
        ),
    ]
