# Generated by Django 4.0.3 on 2022-11-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='access_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.CharField(max_length=1)),
                ('vid', models.IntegerField()),
                ('u_g', models.CharField(default='U', max_length=1)),
                ('u_g_nr', models.IntegerField(default=0)),
                ('r_w', models.CharField(default='R', max_length=1)),
            ],
        ),
    ]
