# Generated by Django 6.0.1 on 2026-01-17 13:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('streams', '0001_initial'), ('streams', '0002_stream_cam_onvif_adminpasswd_and_more'), ('streams', '0003_rename_cam_onvif_ip_stream_cam_control_ip_and_more'), ('streams', '0004_alter_stream_eve_alarm_email'), ('streams', '0005_stream_det_gpu_nr_cv_stream_eve_gpu_nr_cv'), ('streams', '0006_alter_stream_det_erosion'), ('streams', '0007_stream_encrypted'), ('streams', '0008_stream_crypt_key'), ('streams', '0009_alter_stream_crypt_key'), ('streams', '0010_stream_eve_shrink_factor'), ('streams', '0011_alter_stream_det_fpslimit_alter_stream_eve_fpslimit_and_more'), ('streams', '0012_stream_demo'), ('streams', '0013_stream_eve_sync_factor'), ('streams', '0014_stream_cam_red_lat'), ('streams', '0015_remove_stream_cam_feed_type_and_more'), ('streams', '0016_alter_stream_cam_checkdoubles_and_more'), ('streams', '0017_stream_storage_quota'), ('streams', '0018_stream_cam_is_virtual'), ('streams', '0019_remove_stream_cam_is_virtual_stream_cam_virtual_fps'), ('streams', '0020_remove_stream_eve_all_predictions'), ('streams', '0021_alter_stream_cam_fpslimit_alter_stream_eve_fpslimit'), ('streams', '0022_stream_eve_webm_doit'), ('streams', '0023_stream_eve_webm_width_alter_stream_eve_webm_doit'), ('streams', '0024_stream_eve_procnum_limit_stream_eve_webm_crf_and_more'), ('streams', '0025_alter_stream_eve_procnum_limit_and_more'), ('streams', '0026_rename_eve_procnum_limit_stream_eve_webm_procnum_limit'), ('streams', '0027_stream_eve_alarm_max_nr'), ('streams', '0028_alter_stream_eve_alarm_max_nr'), ('streams', '0029_alter_stream_eve_alarm_max_nr'), ('streams', '0030_stream_eve_one_frame_per_event')]

    initial = True

    dependencies = [
        ('tf_workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(default='New Stream', max_length=100)),
                ('made', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastused', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('cam_mode_flag', models.IntegerField(default=2)),
                ('cam_view', models.BooleanField(default=True)),
                ('cam_xres', models.IntegerField(default=0)),
                ('cam_yres', models.IntegerField(default=0)),
                ('cam_fpslimit', models.FloatField(default=0.0, verbose_name='Image FPS limit')),
                ('cam_fpsactual', models.FloatField(default=0)),
                ('cam_url', models.CharField(default='', max_length=256, verbose_name='video url')),
                ('cam_apply_mask', models.BooleanField(default=False)),
                ('cam_checkdoubles', models.BooleanField(default=True, verbose_name='Filter identical frames')),
                ('cam_latency', models.FloatField(default=60.0)),
                ('cam_ffmpeg_fps', models.FloatField(default=6, verbose_name='Video FPS limit')),
                ('cam_ffmpeg_segment', models.FloatField(default=10, verbose_name='ffmpeg segment length')),
                ('cam_ffmpeg_crf', models.IntegerField(default=23, verbose_name='ffmpeg CRF')),
                ('cam_video_codec', models.IntegerField(default=-1)),
                ('cam_audio_codec', models.IntegerField(default=-1)),
                ('cam_max_x_view', models.IntegerField(default=0)),
                ('cam_min_x_view', models.IntegerField(default=0)),
                ('cam_scale_x_view', models.FloatField(default=1.0)),
                ('cam_pause', models.BooleanField(default=False)),
                ('det_mode_flag', models.IntegerField(default=2)),
                ('det_view', models.BooleanField(default=True)),
                ('det_fpslimit', models.FloatField(default=2.0, verbose_name='FPS limit')),
                ('det_fpsactual', models.FloatField(default=0)),
                ('det_threshold', models.IntegerField(default=40, verbose_name='threshold')),
                ('det_backgr_delay', models.IntegerField(default=1, verbose_name='background delay')),
                ('det_dilation', models.IntegerField(default=20, verbose_name='dilation')),
                ('det_erosion', models.IntegerField(default=1, verbose_name='erosion')),
                ('det_max_rect', models.IntegerField(default=20, verbose_name='max. number')),
                ('det_max_size', models.IntegerField(default=100, verbose_name='max. size')),
                ('det_apply_mask', models.BooleanField(default=False)),
                ('det_max_x_view', models.IntegerField(default=0)),
                ('det_min_x_view', models.IntegerField(default=0)),
                ('det_scale_x_view', models.FloatField(default=1.0)),
                ('det_scaledown', models.IntegerField(default=0, verbose_name='scaledown')),
                ('eve_mode_flag', models.IntegerField(default=2)),
                ('eve_view', models.BooleanField(default=True)),
                ('eve_fpslimit', models.FloatField(default=0.0, verbose_name='FPS limit')),
                ('eve_fpsactual', models.FloatField(default=0)),
                ('eve_alarm_email', models.CharField(default='', max_length=255, verbose_name='alarm email')),
                ('eve_event_time_gap', models.IntegerField(default=60, verbose_name='new event gap')),
                ('eve_margin', models.IntegerField(default=20, verbose_name='frame margin')),
                ('eve_school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tf_workers.school')),
                ('eve_max_x_view', models.IntegerField(default=0)),
                ('eve_min_x_view', models.IntegerField(default=0)),
                ('eve_scale_x_view', models.FloatField(default=1.0)),
                ('cam_control_passwd', models.CharField(default='', max_length=256)),
                ('cam_control_user', models.CharField(default='', max_length=256)),
                ('cam_control_ip', models.CharField(default='', max_length=256)),
                ('cam_control_port', models.IntegerField(default=0)),
                ('cam_control_mode', models.IntegerField(choices=[(0, 'Url'), (1, 'ISAPI'), (2, 'ONVIF')], default=0)),
                ('det_gpu_nr_cv', models.IntegerField(default=0)),
                ('eve_gpu_nr_cv', models.IntegerField(default=0)),
                ('encrypted', models.BooleanField(default=True)),
                ('crypt_key', models.BinaryField(default=b'', max_length=256)),
                ('eve_shrink_factor', models.FloatField(default=0.2, verbose_name='shrink factor')),
                ('demo', models.BooleanField(default=False)),
                ('eve_sync_factor', models.FloatField(default=0.0, verbose_name='sync factor')),
                ('cam_red_lat', models.BooleanField(default=True, verbose_name='Reduce latence')),
                ('storage_quota', models.BigIntegerField(default=0)),
                ('cam_virtual_fps', models.FloatField(default=0.0)),
                ('eve_webm_doit', models.BooleanField(default=False)),
                ('eve_webm_width', models.IntegerField(default=500)),
                ('eve_webm_procnum_limit', models.IntegerField(default=1)),
                ('eve_webm_crf', models.IntegerField(default=51)),
                ('eve_webm_fps', models.IntegerField(default=5)),
                ('eve_webm_threads', models.IntegerField(default=1)),
                ('eve_alarm_max_nr', models.IntegerField(default=99, verbose_name='max alarm nr')),
                ('eve_one_frame_per_event', models.BooleanField(default=False, verbose_name='one frame per event')),
            ],
        ),
    ]
