# Generated by Django 4.2.1 on 2023-07-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='cam_onvif_adminpasswd',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='stream',
            name='cam_onvif_adminuser',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='stream',
            name='cam_onvif_ip',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='stream',
            name='cam_onvif_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stream',
            name='cam_url',
            field=models.CharField(default='', max_length=256, verbose_name='video url'),
        ),
    ]
