# Generated by Django 4.0.3 on 2022-11-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='cam_max_x_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='cam_min_x_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='cam_scale_x_view',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='stream',
            name='det_max_x_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='det_min_x_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='det_scale_x_view',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='stream',
            name='eve_max_x_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='eve_min_x_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='eve_scale_x_view',
            field=models.FloatField(default=1.0),
        ),
    ]
