# Generated by Django 4.1.4 on 2023-01-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_stream_cam_max_x_view_stream_cam_min_x_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='cam_pause',
            field=models.BooleanField(default=False),
        ),
    ]
