# Generated by Django 4.2.5 on 2023-12-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_rename_cam_onvif_ip_stream_cam_control_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='eve_alarm_email',
            field=models.CharField(default='', max_length=255, verbose_name='alarm email'),
        ),
    ]
