# Generated by Django 4.2.5 on 2024-01-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_alter_stream_eve_alarm_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='det_gpu_nr_cv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='eve_gpu_nr_cv',
            field=models.IntegerField(default=0),
        ),
    ]
