# Generated by Django 4.2.5 on 2024-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0006_alter_stream_det_erosion'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='encrypted',
            field=models.BooleanField(default=True),
        ),
    ]
