# Generated by Django 4.2.5 on 2024-02-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0007_stream_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='crypt_key',
            field=models.BinaryField(default=b'', max_length=32),
        ),
    ]
