# Generated by Django 4.2.5 on 2024-02-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0008_stream_crypt_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='crypt_key',
            field=models.BinaryField(default=b'', max_length=256),
        ),
    ]
