# Generated by Django 4.2.5 on 2024-03-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0010_stream_eve_shrink_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='det_fpslimit',
            field=models.FloatField(default=2.0, verbose_name='FPS limit'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='eve_fpslimit',
            field=models.FloatField(default=2.0, verbose_name='FPS limit'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='eve_shrink_factor',
            field=models.FloatField(default=0.2, verbose_name='shrink factor'),
        ),
    ]
