# Generated by Django 4.2.5 on 2024-03-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0011_alter_stream_det_fpslimit_alter_stream_eve_fpslimit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
