# Generated by Django 4.2.5 on 2024-03-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0012_stream_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='eve_sync_factor',
            field=models.FloatField(default=0.0, verbose_name='sync factor'),
        ),
    ]
