# Generated by Django 4.2.5 on 2024-06-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0013_stream_eve_sync_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='cam_red_lat',
            field=models.BooleanField(default=True, verbose_name='Red. latence'),
        ),
    ]
