# Generated by Django 4.2.5 on 2024-07-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0014_stream_cam_red_lat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='cam_feed_type',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='cam_repeater',
        ),
    ]
