# Generated by Django 4.2.5 on 2024-07-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0015_remove_stream_cam_feed_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='cam_checkdoubles',
            field=models.BooleanField(default=True, verbose_name='Filter identical frames'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='cam_ffmpeg_fps',
            field=models.FloatField(default=6, verbose_name='Video FPS limit'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='cam_fpslimit',
            field=models.FloatField(default=2.0, verbose_name='Image FPS limit'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='cam_red_lat',
            field=models.BooleanField(default=True, verbose_name='Reduce latence'),
        ),
    ]
