# Generated by Django 4.2.5 on 2024-07-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0016_alter_stream_cam_checkdoubles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='storage_quota',
            field=models.BigIntegerField(default=0),
        ),
    ]
