# Generated by Django 5.1.2 on 2024-11-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0017_stream_storage_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='cam_is_virtual',
            field=models.BooleanField(default=False),
        ),
    ]
