# Generated by Django 5.1.6 on 2025-04-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0020_remove_stream_eve_all_predictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='cam_fpslimit',
            field=models.FloatField(default=0.0, verbose_name='Image FPS limit'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='eve_fpslimit',
            field=models.FloatField(default=0.0, verbose_name='FPS limit'),
        ),
    ]
