# Generated by Django 5.1.6 on 2025-04-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0021_alter_stream_cam_fpslimit_alter_stream_eve_fpslimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='eve_webm_doit',
            field=models.BooleanField(default=True),
        ),
    ]
