# Generated by Django 5.1.6 on 2025-04-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0022_stream_eve_webm_doit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='eve_webm_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stream',
            name='eve_webm_doit',
            field=models.BooleanField(default=False),
        ),
    ]
