# Generated by Django 5.1.6 on 2025-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0023_stream_eve_webm_width_alter_stream_eve_webm_doit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='eve_procnum_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='eve_webm_crf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='eve_webm_fps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='eve_webm_threads',
            field=models.IntegerField(default=0),
        ),
    ]
