# Generated by Django 5.1.6 on 2025-04-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0024_stream_eve_procnum_limit_stream_eve_webm_crf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='eve_procnum_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stream',
            name='eve_webm_crf',
            field=models.IntegerField(default=51),
        ),
        migrations.AlterField(
            model_name='stream',
            name='eve_webm_fps',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='stream',
            name='eve_webm_threads',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stream',
            name='eve_webm_width',
            field=models.IntegerField(default=500),
        ),
    ]
