# Generated by Django 5.1.6 on 2025-04-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0025_alter_stream_eve_procnum_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='eve_procnum_limit',
            new_name='eve_webm_procnum_limit',
        ),
    ]
