# Generated by Django 5.2.1 on 2025-09-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0026_rename_eve_procnum_limit_stream_eve_webm_procnum_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='eve_alarm_max_nr',
            field=models.IntegerField(default=99),
        ),
    ]
