# Generated by Django 5.2.1 on 2025-09-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0028_alter_stream_eve_alarm_max_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='eve_alarm_max_nr',
            field=models.IntegerField(default=99, verbose_name='max alarm nr'),
        ),
    ]
