# Generated by Django 5.2.1 on 2025-09-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0029_alter_stream_eve_alarm_max_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='eve_one_frame_per_event',
            field=models.BooleanField(default=False, verbose_name='one frame per event'),
        ),
    ]
