# Generated by Django 6.0.1 on 2026-02-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_squashed_0030_stream_eve_one_frame_per_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='cam_red_lat',
        ),
        migrations.AddField(
            model_name='stream',
            name='cam_positive_mask',
            field=models.BooleanField(default=True, verbose_name='Positive Mask'),
        ),
        migrations.AddField(
            model_name='stream',
            name='det_positive_mask',
            field=models.BooleanField(default=True, verbose_name='Positive Mask'),
        ),
    ]
