# Generated by Django 6.0.1 on 2026-02-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0031_remove_stream_cam_red_lat_stream_cam_positive_mask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='cam_checkdoubles',
            field=models.BooleanField(default=False, verbose_name='Filter identical frames'),
        ),
    ]
