# Generated by Django 6.0.1 on 2026-03-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0032_alter_stream_cam_checkdoubles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='cam_max_x_view',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='cam_min_x_view',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='cam_scale_x_view',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='det_max_x_view',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='det_min_x_view',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='det_scale_x_view',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='eve_max_x_view',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='eve_min_x_view',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='eve_scale_x_view',
        ),
        migrations.AddField(
            model_name='stream',
            name='cam_scaledown',
            field=models.IntegerField(default=1, verbose_name='scaledown'),
        ),
    ]
