# Generated by Django 6.0.1 on 2026-04-12 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('streams', '0033_remove_stream_cam_max_x_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='det_plugin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.plugin'),
        ),
    ]
