# Generated by Django 6.0.1 on 2026-04-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0034_stream_det_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='det_mode_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
