# Generated by Django 6.0.1 on 2026-04-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0035_stream_det_mode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='det_mode_code',
            field=models.CharField(default='', max_length=50, verbose_name='Detection Mode'),
        ),
    ]
