# Generated by Django 6.0.1 on 2026-04-29 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('streams', '0036_alter_stream_det_mode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='eve_alarm_plugin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='alarm_streams', to='core.plugin'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='det_plugin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='det_streams', to='core.plugin'),
        ),
    ]
