# Generated by Django 6.0.1 on 2026-04-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0037_stream_eve_alarm_plugin_alter_stream_det_plugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='eve_alarm_max_nr',
        ),
    ]
