# Generated by Django 6.0.1 on 2026-05-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0038_remove_stream_eve_alarm_max_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
