# Generated by Django 6.0.1 on 2026-05-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0039_alter_stream_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='det_gpu_nr_cv',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='stream',
            name='eve_gpu_nr_cv',
            field=models.IntegerField(default=-1),
        ),
    ]
