# Generated by Django 6.0.7 on 2026-09-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0040_alter_stream_det_gpu_nr_cv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='eve_one_frame_per_event',
        ),
    ]
