# Generated by Django 4.1.4 on 2022-12-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='locktime',
        ),
    ]
