# Generated by Django 4.0.3 on 2022-11-04 18:55

from django.db import migrations, models
"""
Copyright (C) 2024 by the CAM-AI team, info@cam-ai.de
More information and complete source: https://github.com/ludgerh/cam-ai
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 3
of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
"""

def fill_table_setting(apps, schema_editor):
  Setting = apps.get_model("tools", "setting")
  if not Setting.objects.all().count():
    Setting.objects.create(setting='loglevel', value='INFO', comment='None')
    Setting.objects.create(setting='version', value='0.0.0', comment='None')
    Setting.objects.create(setting='local_trainer', value='0', comment='None')
    Setting.objects.create(setting='system_number', value='-1', comment='None')
    Setting.objects.create(setting='deletethreshold', value='0', comment='None')

class Migration(migrations.Migration):

  initial = True

  dependencies = [
  ]

  operations = [
    migrations.CreateModel(
      name='camurl',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('type', models.CharField(max_length=100)),
        ('url', models.CharField(max_length=255)),
      ],
    ),
    migrations.CreateModel(
      name='setting',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('setting', models.CharField(max_length=100)),
        ('value', models.CharField(max_length=100)),
        ('comment', models.CharField(max_length=255)),
      ],
    ),
    migrations.RunPython(fill_table_setting),
    migrations.CreateModel(
      name='token',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('passwd', models.CharField(max_length=20)),
        ('made', models.DateTimeField()),
        ('count', models.IntegerField(default=0)),
        ('valid', models.BooleanField(default=True)),
        ('cat', models.CharField(default='NON', max_length=3)),
        ('idx', models.IntegerField(default=0)),
        ('info', models.CharField(default='...', max_length=255)),
      ],
    ),
  ]
