# Generated by Django 4.1.4 on 2022-12-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwd', models.CharField(max_length=20)),
                ('made', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
