# Generated by Django 4.2.5 on 2024-06-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camurl',
            name='reduce_latence',
            field=models.BooleanField(default=True),
        ),
    ]
