# Generated by Django 6.0.1 on 2026-02-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_camurl_reduce_latence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camurl',
            name='reduce_latence',
        ),
    ]
