# Generated by Django 4.1.4 on 2022-12-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_token_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='cat',
            field=models.CharField(default='NON', max_length=3),
        ),
        migrations.AddField(
            model_name='token',
            name='idx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='token',
            name='info',
            field=models.CharField(default='...', max_length=255),
        ),
    ]
