# Generated by Django 6.0.1 on 2026-05-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_remove_camurl_reduce_latence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='idx',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
